# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: communication.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'communication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ommunication.proto\x12\rcommunication\"2\n\x0bPingRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"C\n\x0cPongResponse\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0e\n\x06source\x18\x03 \x01(\t\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x9d\x01\n\x0b\x43hatRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12+\n\x07history\x18\x03 \x03(\x0b\x32\x1a.communication.ChatMessage\x12\x15\n\rsystem_prompt\x18\x04 \x01(\t\x12\x14\n\x0c\x63ore_summary\x18\x05 \x01(\t\x12\x11\n\tkey_facts\x18\x06 \x01(\t\"\x9e\x01\n\x17SummarizeContextRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x1c\n\x14\x63urrent_core_summary\x18\x02 \x01(\t\x12\x19\n\x11\x63urrent_key_facts\x18\x03 \x01(\t\x12\x38\n\x14messages_to_compress\x18\x04 \x03(\x0b\x32\x1a.communication.ChatMessage\"]\n\x18SummarizeContextResponse\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x18\n\x10new_core_summary\x18\x02 \x01(\t\x12\x15\n\rnew_key_facts\x18\x03 \x01(\t\"~\n\x12\x43hatStreamResponse\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05\x63hunk\x18\x03 \x01(\t\x12\x13\n\x0bis_finished\x18\x04 \x01(\x08\x12\x15\n\rfinish_reason\x18\x05 \x01(\t\x12\r\n\x05\x65rror\x18\x06 \x01(\t2\x8b\x02\n\x14\x43ommunicationService\x12?\n\x04Ping\x12\x1a.communication.PingRequest\x1a\x1b.communication.PongResponse\x12M\n\nChatStream\x12\x1a.communication.ChatRequest\x1a!.communication.ChatStreamResponse0\x01\x12\x63\n\x10SummarizeContext\x12&.communication.SummarizeContextRequest\x1a\'.communication.SummarizeContextResponseB4Z2luna-ai/backend/runtime/shared/proto/communicationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'communication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2luna-ai/backend/runtime/shared/proto/communication'
  _globals['_PINGREQUEST']._serialized_start=38
  _globals['_PINGREQUEST']._serialized_end=88
  _globals['_PONGRESPONSE']._serialized_start=90
  _globals['_PONGRESPONSE']._serialized_end=157
  _globals['_CHATMESSAGE']._serialized_start=159
  _globals['_CHATMESSAGE']._serialized_end=203
  _globals['_CHATREQUEST']._serialized_start=206
  _globals['_CHATREQUEST']._serialized_end=363
  _globals['_SUMMARIZECONTEXTREQUEST']._serialized_start=366
  _globals['_SUMMARIZECONTEXTREQUEST']._serialized_end=524
  _globals['_SUMMARIZECONTEXTRESPONSE']._serialized_start=526
  _globals['_SUMMARIZECONTEXTRESPONSE']._serialized_end=619
  _globals['_CHATSTREAMRESPONSE']._serialized_start=621
  _globals['_CHATSTREAMRESPONSE']._serialized_end=747
  _globals['_COMMUNICATIONSERVICE']._serialized_start=750
  _globals['_COMMUNICATIONSERVICE']._serialized_end=1017
# @@protoc_insertion_point(module_scope)
