# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# Modified: Added Embedding and Rerank methods (protoc Python gRPC plugin unavailable)
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.api import communication_pb2 as communication__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in communication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CommunicationServiceStub(object):
    """通信服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/communication.CommunicationService/Ping',
                request_serializer=communication__pb2.PingRequest.SerializeToString,
                response_deserializer=communication__pb2.PongResponse.FromString,
                _registered_method=True)
        self.ChatStream = channel.unary_stream(
                '/communication.CommunicationService/ChatStream',
                request_serializer=communication__pb2.ChatRequest.SerializeToString,
                response_deserializer=communication__pb2.ChatStreamResponse.FromString,
                _registered_method=True)
        self.ShortSummarize = channel.unary_unary(
                '/communication.CommunicationService/ShortSummarize',
                request_serializer=communication__pb2.ShortSummarizeRequest.SerializeToString,
                response_deserializer=communication__pb2.ShortSummarizeResponse.FromString,
                _registered_method=True)
        self.SyncPresetConfig = channel.unary_unary(
                '/communication.CommunicationService/SyncPresetConfig',
                request_serializer=communication__pb2.SyncPresetConfigRequest.SerializeToString,
                response_deserializer=communication__pb2.SyncPresetConfigResponse.FromString,
                _registered_method=True)
        self.LongSummarize = channel.unary_unary(
                '/communication.CommunicationService/LongSummarize',
                request_serializer=communication__pb2.LongSummarizeRequest.SerializeToString,
                response_deserializer=communication__pb2.LongSummarizeResponse.FromString,
                _registered_method=True)
        self.Embedding = channel.unary_unary(
                '/communication.CommunicationService/Embedding',
                request_serializer=communication__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=communication__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.Rerank = channel.unary_unary(
                '/communication.CommunicationService/Rerank',
                request_serializer=communication__pb2.RerankRequest.SerializeToString,
                response_deserializer=communication__pb2.RerankResponse.FromString,
                _registered_method=True)


class CommunicationServiceServicer(object):
    """通信服务定义
    """

    def Ping(self, request, context):
        """Ping 方法，用于健康检查和连接测试
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request, context):
        """ChatStream 方法，用于流式对话
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShortSummarize(self, request, context):
        """ShortSummarize 方法，用于后台短期摘要压缩
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncPresetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LongSummarize(self, request, context):
        """LongSummarize 方法，用于长期历史记录压缩
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embedding(self, request, context):
        """Embedding 方法，用于文本向量化
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rerank(self, request, context):
        """Rerank 方法，用于候选文档重排打分
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommunicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=communication__pb2.PingRequest.FromString,
                    response_serializer=communication__pb2.PongResponse.SerializeToString,
            ),
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=communication__pb2.ChatRequest.FromString,
                    response_serializer=communication__pb2.ChatStreamResponse.SerializeToString,
            ),
            'ShortSummarize': grpc.unary_unary_rpc_method_handler(
                    servicer.ShortSummarize,
                    request_deserializer=communication__pb2.ShortSummarizeRequest.FromString,
                    response_serializer=communication__pb2.ShortSummarizeResponse.SerializeToString,
            ),
            'SyncPresetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncPresetConfig,
                    request_deserializer=communication__pb2.SyncPresetConfigRequest.FromString,
                    response_serializer=communication__pb2.SyncPresetConfigResponse.SerializeToString,
            ),
            'LongSummarize': grpc.unary_unary_rpc_method_handler(
                    servicer.LongSummarize,
                    request_deserializer=communication__pb2.LongSummarizeRequest.FromString,
                    response_serializer=communication__pb2.LongSummarizeResponse.SerializeToString,
            ),
            'Embedding': grpc.unary_unary_rpc_method_handler(
                    servicer.Embedding,
                    request_deserializer=communication__pb2.EmbeddingRequest.FromString,
                    response_serializer=communication__pb2.EmbeddingResponse.SerializeToString,
            ),
            'Rerank': grpc.unary_unary_rpc_method_handler(
                    servicer.Rerank,
                    request_deserializer=communication__pb2.RerankRequest.FromString,
                    response_serializer=communication__pb2.RerankResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'communication.CommunicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('communication.CommunicationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CommunicationService(object):
    """通信服务定义
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/communication.CommunicationService/Ping',
            communication__pb2.PingRequest.SerializeToString,
            communication__pb2.PongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/communication.CommunicationService/ChatStream',
            communication__pb2.ChatRequest.SerializeToString,
            communication__pb2.ChatStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShortSummarize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/communication.CommunicationService/ShortSummarize',
            communication__pb2.ShortSummarizeRequest.SerializeToString,
            communication__pb2.ShortSummarizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncPresetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/communication.CommunicationService/SyncPresetConfig',
            communication__pb2.SyncPresetConfigRequest.SerializeToString,
            communication__pb2.SyncPresetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LongSummarize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/communication.CommunicationService/LongSummarize',
            communication__pb2.LongSummarizeRequest.SerializeToString,
            communication__pb2.LongSummarizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/communication.CommunicationService/Embedding',
            communication__pb2.EmbeddingRequest.SerializeToString,
            communication__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rerank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/communication.CommunicationService/Rerank',
            communication__pb2.RerankRequest.SerializeToString,
            communication__pb2.RerankResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
