export const EMOTION_EXPRESSIONS = {
  Angry: ["眼-生气", "脸红2隐藏"],
  Annoyed: ["眼-生气", "脸黑", "脸红2隐藏"],
  Irritated: ["眼-生气"],
  Sad: ["眼-哭哭"],
  Lonely: ["眼-泪眼汪汪"],
  Despair: ["脸黑", "脸红2隐藏"],
  Broken: ["脸黑", "眼-眩晕流汗", "脸红2隐藏"],
  Uneasy: ["眼-哭哭"],
  Anxious: ["眼-眩晕流汗", "脸红"],
  Fearful: ["眼-哭哭", "脸黑"],
  Shocked: ["眼-眩晕流汗"],
  Tired: ["脸红2隐藏", "眼-平静死鱼眼"],
  Bored: ["眼-平静死鱼眼"],
  Confused: ["眼-眩晕流汗"],
  Disappointed: ["脸黑"],
  Frustrated: ["眼-哭哭"],
  Embarrassed: ["嘴-平静v形（不可张开", "脸红"],
  Flustered: ["眼-眩晕流汗", "脸红"],
  Affectionate: ["嘴-平静v形（不可张开", "脸红"],
  Clingy: ["眼-星星眼", "脸红"],
  Teasing: ["脸红-痴汉嘴（兼容吐舌", "脸红", "眼-平静死鱼眼"],
  Tsundere: ["脸红"],
  Yandere: ["脸黑", "脸红", "嘴-平静v形（不可张开", "眼-爱心眼"],
  Smile: ["嘴-平静v形（不可张开"],
  Soft: ["嘴-平静v形（不可张开", "脸红"],
  Shy: ["嘴-平静v形（不可张开", "脸红"],
  Hopeful: ["眼-星星眼"],
  Grateful: ["眼-泪眼汪汪", "脸红"],
  Solemn: [],
  Determined: ["眼-生气"],
  Proud: ["眼-星星眼"],
  Relieved: ["嘴-平静v形（不可张开", "眼-泪眼汪汪"],
  Resigned: ["眼-平静死鱼眼", "脸黑"]
} as const;
