// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: communication.proto

// 通信模块的协议定义
// 本文件定义 Luna AI 各层之间（Go Runtime <-> Python AI Service）的 gRPC 通信协议

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ping 请求消息
type PingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 跟踪ID，用于请求追踪
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// 时间戳，记录请求发起的时间
	Timestamp     int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_communication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Pong 响应消息
type PongResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 跟踪ID，用于请求追踪
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// 时间戳，记录响应返回的时间
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 源信息，表示响应来源
	Source        string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_communication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{1}
}

func (x *PongResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *PongResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PongResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// ChatMessage 定义单条对话消息，用于多轮对话历史记录
type ChatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色：system / user / assistant
	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// 消息文本内容
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// 是否为错误消息
	IsError bool `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	// 错误详情
	ErrorDetails  string `protobuf:"bytes,4,opt,name=error_details,json=errorDetails,proto3" json:"error_details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_communication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *ChatMessage) GetErrorDetails() string {
	if x != nil {
		return x.ErrorDetails
	}
	return ""
}

// Chat 请求消息
type ChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 跟踪ID，用于请求追踪
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// 用户输入的消息内容
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 多轮对话历史记录列表，不包含当前 message
	// 前端维护的历史记录，按时间正序排列（最旧的在最前）
	History []*ChatMessage `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	// 完整的系统提示词（包含 personality、memory、runtime 等所有上下文层）
	SystemPrompt  string `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_communication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{3}
}

func (x *ChatRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *ChatRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

// SummarizeContext 请求消息
type SummarizeContextRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 跟踪ID，用于请求追踪
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// 已渲染好的完整摘要压缩提示词
	SummarizePrompt string `protobuf:"bytes,2,opt,name=summarize_prompt,json=summarizePrompt,proto3" json:"summarize_prompt,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SummarizeContextRequest) Reset() {
	*x = SummarizeContextRequest{}
	mi := &file_communication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeContextRequest) ProtoMessage() {}

func (x *SummarizeContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeContextRequest.ProtoReflect.Descriptor instead.
func (*SummarizeContextRequest) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{4}
}

func (x *SummarizeContextRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SummarizeContextRequest) GetSummarizePrompt() string {
	if x != nil {
		return x.SummarizePrompt
	}
	return ""
}

// SummarizeContext 响应消息
type SummarizeContextResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 跟踪ID，用于请求追踪
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// 新的 core_summary
	NewCoreSummary string `protobuf:"bytes,2,opt,name=new_core_summary,json=newCoreSummary,proto3" json:"new_core_summary,omitempty"`
	// 新的 key_facts
	NewKeyFacts string `protobuf:"bytes,3,opt,name=new_key_facts,json=newKeyFacts,proto3" json:"new_key_facts,omitempty"`
	// 新的 short_term_memory
	NewShortTermMemory string `protobuf:"bytes,4,opt,name=new_short_term_memory,json=newShortTermMemory,proto3" json:"new_short_term_memory,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SummarizeContextResponse) Reset() {
	*x = SummarizeContextResponse{}
	mi := &file_communication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeContextResponse) ProtoMessage() {}

func (x *SummarizeContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeContextResponse.ProtoReflect.Descriptor instead.
func (*SummarizeContextResponse) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{5}
}

func (x *SummarizeContextResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SummarizeContextResponse) GetNewCoreSummary() string {
	if x != nil {
		return x.NewCoreSummary
	}
	return ""
}

func (x *SummarizeContextResponse) GetNewKeyFacts() string {
	if x != nil {
		return x.NewKeyFacts
	}
	return ""
}

func (x *SummarizeContextResponse) GetNewShortTermMemory() string {
	if x != nil {
		return x.NewShortTermMemory
	}
	return ""
}

// Chat 流式响应消息
type ChatStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 跟踪ID，用于请求追踪
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// 消息类型："thought_content"（内心独白）/"emotion_update"（情绪更新）/"reply_chunk"（回复文本片段）
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// 文本块内容（情绪枚举值 / 内心独白文本 / 经过缓冲合并后的短语/短句）
	Chunk string `protobuf:"bytes,3,opt,name=chunk,proto3" json:"chunk,omitempty"`
	// 是否结束
	IsFinished bool `protobuf:"varint,4,opt,name=is_finished,json=isFinished,proto3" json:"is_finished,omitempty"`
	// 结束原因 (stop / length / error)
	FinishReason string `protobuf:"bytes,5,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	// 错误信息，仅当 finish_reason = "error" 时非空
	Error         string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamResponse) Reset() {
	*x = ChatStreamResponse{}
	mi := &file_communication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamResponse) ProtoMessage() {}

func (x *ChatStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamResponse.ProtoReflect.Descriptor instead.
func (*ChatStreamResponse) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{6}
}

func (x *ChatStreamResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ChatStreamResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatStreamResponse) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

func (x *ChatStreamResponse) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

func (x *ChatStreamResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *ChatStreamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ModelConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl       string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"` // 明文，仅在内存中流转
	ModelId       string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"` // 0 表示无上限
	Temperature   float32                `protobuf:"fixed32,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelConfig) Reset() {
	*x = ModelConfig{}
	mi := &file_communication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelConfig) ProtoMessage() {}

func (x *ModelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelConfig.ProtoReflect.Descriptor instead.
func (*ModelConfig) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{7}
}

func (x *ModelConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ModelConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ModelConfig) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelConfig) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ModelConfig) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

// 预设配置同步请求
type SyncPresetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // 必须包含版本号，例如 "v1.0"
	PresetId      string                 `protobuf:"bytes,2,opt,name=preset_id,json=presetId,proto3" json:"preset_id,omitempty"`
	LargeModel    *ModelConfig           `protobuf:"bytes,3,opt,name=large_model,json=largeModel,proto3" json:"large_model,omitempty"`
	MediumModel   *ModelConfig           `protobuf:"bytes,4,opt,name=medium_model,json=mediumModel,proto3" json:"medium_model,omitempty"`
	SmallModel    *ModelConfig           `protobuf:"bytes,5,opt,name=small_model,json=smallModel,proto3" json:"small_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPresetConfigRequest) Reset() {
	*x = SyncPresetConfigRequest{}
	mi := &file_communication_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPresetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPresetConfigRequest) ProtoMessage() {}

func (x *SyncPresetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPresetConfigRequest.ProtoReflect.Descriptor instead.
func (*SyncPresetConfigRequest) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{8}
}

func (x *SyncPresetConfigRequest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *SyncPresetConfigRequest) GetPresetId() string {
	if x != nil {
		return x.PresetId
	}
	return ""
}

func (x *SyncPresetConfigRequest) GetLargeModel() *ModelConfig {
	if x != nil {
		return x.LargeModel
	}
	return nil
}

func (x *SyncPresetConfigRequest) GetMediumModel() *ModelConfig {
	if x != nil {
		return x.MediumModel
	}
	return nil
}

func (x *SyncPresetConfigRequest) GetSmallModel() *ModelConfig {
	if x != nil {
		return x.SmallModel
	}
	return nil
}

// 预设配置同步响应
type SyncPresetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPresetConfigResponse) Reset() {
	*x = SyncPresetConfigResponse{}
	mi := &file_communication_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPresetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPresetConfigResponse) ProtoMessage() {}

func (x *SyncPresetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPresetConfigResponse.ProtoReflect.Descriptor instead.
func (*SyncPresetConfigResponse) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{9}
}

func (x *SyncPresetConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncPresetConfigResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_communication_proto protoreflect.FileDescriptor

const file_communication_proto_rawDesc = "" +
	"\n" +
	"\x13communication.proto\x12\rcommunication\"F\n" +
	"\vPingRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"_\n" +
	"\fPongResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\"{\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError\x12#\n" +
	"\rerror_details\x18\x04 \x01(\tR\ferrorDetails\"\x9d\x01\n" +
	"\vChatRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\ahistory\x18\x03 \x03(\v2\x1a.communication.ChatMessageR\ahistory\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\"_\n" +
	"\x17SummarizeContextRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12)\n" +
	"\x10summarize_prompt\x18\x02 \x01(\tR\x0fsummarizePrompt\"\xb6\x01\n" +
	"\x18SummarizeContextResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12(\n" +
	"\x10new_core_summary\x18\x02 \x01(\tR\x0enewCoreSummary\x12\"\n" +
	"\rnew_key_facts\x18\x03 \x01(\tR\vnewKeyFacts\x121\n" +
	"\x15new_short_term_memory\x18\x04 \x01(\tR\x12newShortTermMemory\"\xb5\x01\n" +
	"\x12ChatStreamResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05chunk\x18\x03 \x01(\tR\x05chunk\x12\x1f\n" +
	"\vis_finished\x18\x04 \x01(\bR\n" +
	"isFinished\x12#\n" +
	"\rfinish_reason\x18\x05 \x01(\tR\ffinishReason\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\x9d\x01\n" +
	"\vModelConfig\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x05 \x01(\x02R\vtemperature\"\x96\x02\n" +
	"\x17SyncPresetConfigRequest\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x1b\n" +
	"\tpreset_id\x18\x02 \x01(\tR\bpresetId\x12;\n" +
	"\vlarge_model\x18\x03 \x01(\v2\x1a.communication.ModelConfigR\n" +
	"largeModel\x12=\n" +
	"\fmedium_model\x18\x04 \x01(\v2\x1a.communication.ModelConfigR\vmediumModel\x12;\n" +
	"\vsmall_model\x18\x05 \x01(\v2\x1a.communication.ModelConfigR\n" +
	"smallModel\"Y\n" +
	"\x18SyncPresetConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\xf0\x02\n" +
	"\x14CommunicationService\x12?\n" +
	"\x04Ping\x12\x1a.communication.PingRequest\x1a\x1b.communication.PongResponse\x12M\n" +
	"\n" +
	"ChatStream\x12\x1a.communication.ChatRequest\x1a!.communication.ChatStreamResponse0\x01\x12c\n" +
	"\x10SummarizeContext\x12&.communication.SummarizeContextRequest\x1a'.communication.SummarizeContextResponse\x12c\n" +
	"\x10SyncPresetConfig\x12&.communication.SyncPresetConfigRequest\x1a'.communication.SyncPresetConfigResponseB&Z$luna-ai/backend/runtime/shared/protob\x06proto3"

var (
	file_communication_proto_rawDescOnce sync.Once
	file_communication_proto_rawDescData []byte
)

func file_communication_proto_rawDescGZIP() []byte {
	file_communication_proto_rawDescOnce.Do(func() {
		file_communication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_communication_proto_rawDesc), len(file_communication_proto_rawDesc)))
	})
	return file_communication_proto_rawDescData
}

var file_communication_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_communication_proto_goTypes = []any{
	(*PingRequest)(nil),              // 0: communication.PingRequest
	(*PongResponse)(nil),             // 1: communication.PongResponse
	(*ChatMessage)(nil),              // 2: communication.ChatMessage
	(*ChatRequest)(nil),              // 3: communication.ChatRequest
	(*SummarizeContextRequest)(nil),  // 4: communication.SummarizeContextRequest
	(*SummarizeContextResponse)(nil), // 5: communication.SummarizeContextResponse
	(*ChatStreamResponse)(nil),       // 6: communication.ChatStreamResponse
	(*ModelConfig)(nil),              // 7: communication.ModelConfig
	(*SyncPresetConfigRequest)(nil),  // 8: communication.SyncPresetConfigRequest
	(*SyncPresetConfigResponse)(nil), // 9: communication.SyncPresetConfigResponse
}
var file_communication_proto_depIdxs = []int32{
	2, // 0: communication.ChatRequest.history:type_name -> communication.ChatMessage
	7, // 1: communication.SyncPresetConfigRequest.large_model:type_name -> communication.ModelConfig
	7, // 2: communication.SyncPresetConfigRequest.medium_model:type_name -> communication.ModelConfig
	7, // 3: communication.SyncPresetConfigRequest.small_model:type_name -> communication.ModelConfig
	0, // 4: communication.CommunicationService.Ping:input_type -> communication.PingRequest
	3, // 5: communication.CommunicationService.ChatStream:input_type -> communication.ChatRequest
	4, // 6: communication.CommunicationService.SummarizeContext:input_type -> communication.SummarizeContextRequest
	8, // 7: communication.CommunicationService.SyncPresetConfig:input_type -> communication.SyncPresetConfigRequest
	1, // 8: communication.CommunicationService.Ping:output_type -> communication.PongResponse
	6, // 9: communication.CommunicationService.ChatStream:output_type -> communication.ChatStreamResponse
	5, // 10: communication.CommunicationService.SummarizeContext:output_type -> communication.SummarizeContextResponse
	9, // 11: communication.CommunicationService.SyncPresetConfig:output_type -> communication.SyncPresetConfigResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_communication_proto_init() }
func file_communication_proto_init() {
	if File_communication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_communication_proto_rawDesc), len(file_communication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_communication_proto_goTypes,
		DependencyIndexes: file_communication_proto_depIdxs,
		MessageInfos:      file_communication_proto_msgTypes,
	}.Build()
	File_communication_proto = out.File
	file_communication_proto_goTypes = nil
	file_communication_proto_depIdxs = nil
}
