// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: communication.proto

// 通信模块的协议定义
// 本文件定义 Luna AI 各层之间（Go Runtime <-> Python AI Service）的 gRPC 通信协议

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ping 请求消息
type PingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 跟踪ID，用于请求追踪
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// 时间戳，记录请求发起的时间
	Timestamp     int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_communication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Pong 响应消息
type PongResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 跟踪ID，用于请求追踪
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// 时间戳，记录响应返回的时间
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 源信息，表示响应来源
	Source        string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_communication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{1}
}

func (x *PongResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *PongResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PongResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// ChatMessage 定义单条对话消息，用于多轮对话历史记录
type ChatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色：system / user / assistant
	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// 消息文本内容
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// 是否为错误消息
	IsError bool `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	// 错误详情
	ErrorDetails  string `protobuf:"bytes,4,opt,name=error_details,json=errorDetails,proto3" json:"error_details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_communication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *ChatMessage) GetErrorDetails() string {
	if x != nil {
		return x.ErrorDetails
	}
	return ""
}

// Chat 请求消息
type ChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 跟踪ID，用于请求追踪
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// 用户输入的消息内容
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 多轮对话历史记录列表，不包含当前 message
	// 前端维护的历史记录，按时间正序排列（最旧的在最前）
	History []*ChatMessage `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	// 系统提示词，为空时 Python 侧使用默认提示词
	SystemPrompt string `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	// 核心摘要
	// 核心摘要
	CoreSummary string `protobuf:"bytes,5,opt,name=core_summary,json=coreSummary,proto3" json:"core_summary,omitempty"`
	// 关键事实
	KeyFacts string `protobuf:"bytes,6,opt,name=key_facts,json=keyFacts,proto3" json:"key_facts,omitempty"`
	// 短期记忆（用于渲染 memory.j2 模板的短期记忆文本）
	ShortTermMemory string `protobuf:"bytes,7,opt,name=short_term_memory,json=shortTermMemory,proto3" json:"short_term_memory,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_communication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{3}
}

func (x *ChatRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *ChatRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *ChatRequest) GetCoreSummary() string {
	if x != nil {
		return x.CoreSummary
	}
	return ""
}

func (x *ChatRequest) GetKeyFacts() string {
	if x != nil {
		return x.KeyFacts
	}
	return ""
}

func (x *ChatRequest) GetShortTermMemory() string {
	if x != nil {
		return x.ShortTermMemory
	}
	return ""
}

// SummarizeContext 请求消息
type SummarizeContextRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 跟踪ID，用于请求追踪
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// 当前的 core_summary
	CurrentCoreSummary string `protobuf:"bytes,2,opt,name=current_core_summary,json=currentCoreSummary,proto3" json:"current_core_summary,omitempty"`
	// 当前的 key_facts
	CurrentKeyFacts string `protobuf:"bytes,3,opt,name=current_key_facts,json=currentKeyFacts,proto3" json:"current_key_facts,omitempty"`
	// 需要被压缩的旧消息列表
	MessagesToCompress []*ChatMessage `protobuf:"bytes,4,rep,name=messages_to_compress,json=messagesToCompress,proto3" json:"messages_to_compress,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SummarizeContextRequest) Reset() {
	*x = SummarizeContextRequest{}
	mi := &file_communication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeContextRequest) ProtoMessage() {}

func (x *SummarizeContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeContextRequest.ProtoReflect.Descriptor instead.
func (*SummarizeContextRequest) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{4}
}

func (x *SummarizeContextRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SummarizeContextRequest) GetCurrentCoreSummary() string {
	if x != nil {
		return x.CurrentCoreSummary
	}
	return ""
}

func (x *SummarizeContextRequest) GetCurrentKeyFacts() string {
	if x != nil {
		return x.CurrentKeyFacts
	}
	return ""
}

func (x *SummarizeContextRequest) GetMessagesToCompress() []*ChatMessage {
	if x != nil {
		return x.MessagesToCompress
	}
	return nil
}

// SummarizeContext 响应消息
type SummarizeContextResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 跟踪ID，用于请求追踪
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// 新的 core_summary
	NewCoreSummary string `protobuf:"bytes,2,opt,name=new_core_summary,json=newCoreSummary,proto3" json:"new_core_summary,omitempty"`
	// 新的 key_facts
	NewKeyFacts string `protobuf:"bytes,3,opt,name=new_key_facts,json=newKeyFacts,proto3" json:"new_key_facts,omitempty"`
	// 新的 short_term_memory
	NewShortTermMemory string `protobuf:"bytes,4,opt,name=new_short_term_memory,json=newShortTermMemory,proto3" json:"new_short_term_memory,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SummarizeContextResponse) Reset() {
	*x = SummarizeContextResponse{}
	mi := &file_communication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeContextResponse) ProtoMessage() {}

func (x *SummarizeContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeContextResponse.ProtoReflect.Descriptor instead.
func (*SummarizeContextResponse) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{5}
}

func (x *SummarizeContextResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SummarizeContextResponse) GetNewCoreSummary() string {
	if x != nil {
		return x.NewCoreSummary
	}
	return ""
}

func (x *SummarizeContextResponse) GetNewKeyFacts() string {
	if x != nil {
		return x.NewKeyFacts
	}
	return ""
}

func (x *SummarizeContextResponse) GetNewShortTermMemory() string {
	if x != nil {
		return x.NewShortTermMemory
	}
	return ""
}

// Chat 流式响应消息
type ChatStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 跟踪ID，用于请求追踪
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// 消息类型："thought_content"（内心独白）/"emotion_update"（情绪更新）/"reply_chunk"（回复文本片段）
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// 文本块内容（情绪枚举值 / 内心独白文本 / 经过缓冲合并后的短语/短句）
	Chunk string `protobuf:"bytes,3,opt,name=chunk,proto3" json:"chunk,omitempty"`
	// 是否结束
	IsFinished bool `protobuf:"varint,4,opt,name=is_finished,json=isFinished,proto3" json:"is_finished,omitempty"`
	// 结束原因 (stop / length / error)
	FinishReason string `protobuf:"bytes,5,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	// 错误信息，仅当 finish_reason = "error" 时非空
	Error         string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamResponse) Reset() {
	*x = ChatStreamResponse{}
	mi := &file_communication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamResponse) ProtoMessage() {}

func (x *ChatStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamResponse.ProtoReflect.Descriptor instead.
func (*ChatStreamResponse) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{6}
}

func (x *ChatStreamResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ChatStreamResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatStreamResponse) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

func (x *ChatStreamResponse) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

func (x *ChatStreamResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *ChatStreamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_communication_proto protoreflect.FileDescriptor

const file_communication_proto_rawDesc = "" +
	"\n" +
	"\x13communication.proto\x12\rcommunication\"F\n" +
	"\vPingRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"_\n" +
	"\fPongResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\"{\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError\x12#\n" +
	"\rerror_details\x18\x04 \x01(\tR\ferrorDetails\"\x89\x02\n" +
	"\vChatRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\ahistory\x18\x03 \x03(\v2\x1a.communication.ChatMessageR\ahistory\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\x12!\n" +
	"\fcore_summary\x18\x05 \x01(\tR\vcoreSummary\x12\x1b\n" +
	"\tkey_facts\x18\x06 \x01(\tR\bkeyFacts\x12*\n" +
	"\x11short_term_memory\x18\a \x01(\tR\x0fshortTermMemory\"\xe0\x01\n" +
	"\x17SummarizeContextRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x120\n" +
	"\x14current_core_summary\x18\x02 \x01(\tR\x12currentCoreSummary\x12*\n" +
	"\x11current_key_facts\x18\x03 \x01(\tR\x0fcurrentKeyFacts\x12L\n" +
	"\x14messages_to_compress\x18\x04 \x03(\v2\x1a.communication.ChatMessageR\x12messagesToCompress\"\xb6\x01\n" +
	"\x18SummarizeContextResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12(\n" +
	"\x10new_core_summary\x18\x02 \x01(\tR\x0enewCoreSummary\x12\"\n" +
	"\rnew_key_facts\x18\x03 \x01(\tR\vnewKeyFacts\x121\n" +
	"\x15new_short_term_memory\x18\x04 \x01(\tR\x12newShortTermMemory\"\xb5\x01\n" +
	"\x12ChatStreamResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05chunk\x18\x03 \x01(\tR\x05chunk\x12\x1f\n" +
	"\vis_finished\x18\x04 \x01(\bR\n" +
	"isFinished\x12#\n" +
	"\rfinish_reason\x18\x05 \x01(\tR\ffinishReason\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error2\x8b\x02\n" +
	"\x14CommunicationService\x12?\n" +
	"\x04Ping\x12\x1a.communication.PingRequest\x1a\x1b.communication.PongResponse\x12M\n" +
	"\n" +
	"ChatStream\x12\x1a.communication.ChatRequest\x1a!.communication.ChatStreamResponse0\x01\x12c\n" +
	"\x10SummarizeContext\x12&.communication.SummarizeContextRequest\x1a'.communication.SummarizeContextResponseB&Z$luna-ai/backend/runtime/shared/protob\x06proto3"

var (
	file_communication_proto_rawDescOnce sync.Once
	file_communication_proto_rawDescData []byte
)

func file_communication_proto_rawDescGZIP() []byte {
	file_communication_proto_rawDescOnce.Do(func() {
		file_communication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_communication_proto_rawDesc), len(file_communication_proto_rawDesc)))
	})
	return file_communication_proto_rawDescData
}

var file_communication_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_communication_proto_goTypes = []any{
	(*PingRequest)(nil),              // 0: communication.PingRequest
	(*PongResponse)(nil),             // 1: communication.PongResponse
	(*ChatMessage)(nil),              // 2: communication.ChatMessage
	(*ChatRequest)(nil),              // 3: communication.ChatRequest
	(*SummarizeContextRequest)(nil),  // 4: communication.SummarizeContextRequest
	(*SummarizeContextResponse)(nil), // 5: communication.SummarizeContextResponse
	(*ChatStreamResponse)(nil),       // 6: communication.ChatStreamResponse
}
var file_communication_proto_depIdxs = []int32{
	2, // 0: communication.ChatRequest.history:type_name -> communication.ChatMessage
	2, // 1: communication.SummarizeContextRequest.messages_to_compress:type_name -> communication.ChatMessage
	0, // 2: communication.CommunicationService.Ping:input_type -> communication.PingRequest
	3, // 3: communication.CommunicationService.ChatStream:input_type -> communication.ChatRequest
	4, // 4: communication.CommunicationService.SummarizeContext:input_type -> communication.SummarizeContextRequest
	1, // 5: communication.CommunicationService.Ping:output_type -> communication.PongResponse
	6, // 6: communication.CommunicationService.ChatStream:output_type -> communication.ChatStreamResponse
	5, // 7: communication.CommunicationService.SummarizeContext:output_type -> communication.SummarizeContextResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_communication_proto_init() }
func file_communication_proto_init() {
	if File_communication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_communication_proto_rawDesc), len(file_communication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_communication_proto_goTypes,
		DependencyIndexes: file_communication_proto_depIdxs,
		MessageInfos:      file_communication_proto_msgTypes,
	}.Build()
	File_communication_proto = out.File
	file_communication_proto_goTypes = nil
	file_communication_proto_depIdxs = nil
}
