from enum import Enum

class Role(str, Enum):
    """全局统一的角色枚举"""
    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"

# WebSocket 消息类型常量
WS_MSG_TYPE_PING = "PING"
WS_MSG_TYPE_PONG = "PONG"
WS_MSG_TYPE_CHAT_STREAM = "CHAT_STREAM"
WS_MSG_TYPE_ERROR = "ERROR"
WS_MSG_TYPE_CMD_SYNC_INIT_STATE = "CMD_SYNC_INIT_STATE"
WS_MSG_TYPE_CMD_USER_INPUT = "CMD_USER_INPUT"
WS_MSG_TYPE_EVT_INIT_STATE = "EVT_INIT_STATE"
WS_MSG_TYPE_REQ_GET_CALENDAR_METADATA = "REQ_GET_CALENDAR_METADATA"
WS_MSG_TYPE_RES_CALENDAR_METADATA = "RES_CALENDAR_METADATA"
WS_MSG_TYPE_REQ_GET_CHAT_HISTORY = "REQ_GET_CHAT_HISTORY"
WS_MSG_TYPE_RES_CHAT_HISTORY = "RES_CHAT_HISTORY"
WS_MSG_TYPE_EVT_MEMORY_SYNC = "EVT_MEMORY_SYNC"

# 健康检查状态常量
HEALTH_STATUS_HEALTHY = "healthy"
HEALTH_STATUS_UNHEALTHY = "unhealthy"
HEALTH_STATUS_DEGRADED = "degraded"

class PrimaryIntent(str, Enum):
    MODIFY_PLAN = "MODIFY_PLAN"
    GREETING = "GREETING"
    QUERY_INFO = "QUERY_INFO"
    EMOTION_VENTING = "EMOTION_VENTING"
    SYSTEM_COMMAND = "SYSTEM_COMMAND"
    TOOL_INVOCATION = "TOOL_INVOCATION"

class IntentCategory(str, Enum):
    TASK_MANAGEMENT = "TASK_MANAGEMENT"
    CHAT = "CHAT"
    KNOWLEDGE_QUERY = "KNOWLEDGE_QUERY"
    EMOTION_SUPPORT = "EMOTION_SUPPORT"

class DagRouteHint(str, Enum):
    MULTI_SOURCE_RETRIEVAL_WORKFLOW = "MULTI_SOURCE_RETRIEVAL_WORKFLOW"
    FAST_CHAT = "FAST_CHAT"
    AGENTIC_WORKFLOW = "AGENTIC_WORKFLOW"
    GATING_APPROVAL = "GATING_APPROVAL"

class RetrievalType(str, Enum):
    LONG_TERM_MEMORY = "LONG_TERM_MEMORY"
    EXTERNAL_KNOWLEDGE = "EXTERNAL_KNOWLEDGE"
    EXPERIENCE_REFLECTION = "EXPERIENCE_REFLECTION"
